# Generated by Django 3.0.4 on 2020-06-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200608_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
    ]
