# Generated by Django 3.0.4 on 2020-06-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200608_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='price',
        ),
    ]
